# Example parameters with small ranges
# AXI_ID_WIDTH 1-100
# BAUD_RATE 1-100
# CLK_FREQ 1-100
AXI_DATA_WIDTH 1-100
ADDR_WIDTH 2-2
# ID_W_WIDTH 1-100
# ID_R_WIDTH 1-100
MAX_ROUTERS_X 1-100
# MAX_ROUTERS_X_WIDTH 1-100
MAX_ROUTERS_Y 1-100
# MAX_ROUTERS_Y_WIDTH 1-100
# AXI_MASTER_LOADER_FIFO_DEPTH 1-100
AXI_DATA_BYTES 1-100
# ID_WIDTH 1-100
# DEST_WIDTH 1-100
# USER_WIDTH 1-100
