package require ::quartus::project
package require ::quartus::flow

proc usage {} {
    puts "Usage:"
    puts "  quartus_sh -t compile_with_defines.tcl --project <name> ?--rev <revision>? ?--define NAME[=VALUE] ...?"
    exit 2
}

set project_name ""
set revision_name ""
set defines {}

# Parse command-line arguments
set i 0
while {$i < [llength $argv]} {
    set a [lindex $argv $i]
    switch -- $a {
        --project {
            incr i
            if {$i >= [llength $argv]} { usage }
            set project_name [lindex $argv $i]
        }
        --rev - --revision {
            incr i
            if {$i >= [llength $argv]} { usage }
            set revision_name [lindex $argv $i]
        }
        --define {
            incr i
            if {$i >= [llength $argv]} { usage }
            lappend defines [lindex $argv $i]
        }
        -h - --help {
            usage
        }
        default {
            puts "Unknown argument: $a"
            usage
        }
    }
    incr i
}

# Validate required arguments
if {$project_name eq ""} {
    puts "ERROR: --project is required"
    usage
}

if {$revision_name eq ""} {
    set revision_name $project_name
}

# ----------------------------------------------------------------------
# Generate inc/defines.svh from the collected defines
# ----------------------------------------------------------------------
set defines_dir "inc"
set defines_file "${defines_dir}/defines.svh"

# Delete existing file if it exists
if {[file exists $defines_file]} {
    puts "Removing existing $defines_file ..."
    file delete $defines_file
}

# Create the directory if it doesn't exist
if {![file exists $defines_dir]} {
    puts "Creating directory $defines_dir ..."
    file mkdir $defines_dir
}

# Write the new defines file
puts "Creating $defines_file ..."
set fout [open $defines_file w]
puts $fout "// Auto-generated by compile_with_defines.tcl"
puts $fout "// Do not edit manually."

foreach d $defines {
    set d [string trim $d]
    if {$d eq ""} {
        continue
    }
    if {[regexp {^([^=]+)=(.*)$} $d -> name value]} {
        puts $fout "`define $name $value"
    } else {
        puts $fout "`define $d"
    }
}
close $fout
puts "Defines written to $defines_file"

# ----------------------------------------------------------------------
# Open Quartus project and run compilation
# ----------------------------------------------------------------------
puts "Opening Quartus project '$project_name' (revision '$revision_name') ..."
if {$revision_name eq ""} {
    project_open $project_name
} else {
    project_open $project_name -revision $revision_name
}

puts "Starting Quartus compile ..."
if {[catch {execute_flow -compile} err]} {
    puts "ERROR: Compilation failed:"
    puts $err
    project_close
    exit 1
}

puts "Compile finished."

# ----------------------------------------------------------------------
# Archive the project
# ----------------------------------------------------------------------
puts "Exporting project to ${project_name}.qar ..."
project_archive ${project_name}.qar -overwrite -include_outputs
# -include_libraries
puts "Project exported successfully."

project_close
exit 0
